kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: social
  name: social-delay
spec:
  selector:
    namespaces:
      - social
    labelSelectors:
      vecro-sim/service-name: write-graph
  mode: all
  action: delay
  duration: 15m
  delay:
    latency: 400ms
    correlation: '25'
    jitter: 150ms
  direction: to
